#! /bin/bash

if [[ ! -z "$DX_DEBUG" ]]; then
  exec deno run \
    --inspect-brk \
    --unstable \
    --allow-read \
    --allow-write \
    --allow-net \
    --allow-run \
    --allow-env \
    dx.ts \
    "$@"
else
  exec deno run \
    --unstable \
    --allow-read \
    --allow-write \
    --allow-net \
    --allow-run \
    --allow-env \
    dx.ts \
    "$@"
fi

